### ISSUE TITLE
Include filter uses relative path / revisit sources/include/exclude

### ISSUE THREAD

**Issue by blueyed** [RPGillespie6/fastcov#17]
Code: https://github.com/RPGillespie6/fastcov/blob/79594a8f880c41b207c063007de9171251abca7a/fastcov.py#L132-L138

For me it looks like this there:
```
(Pdb++) gcov['file']
'../src/nvim/version.c'
(Pdb++) gcov['file_abs']
'/home/user/Vcs/neovim/src/nvim/version.c'
```

Therefore it should probably use "file_abs" there (like with "sources" above).

And apart from that it should also either use `fnmatch` (https://docs.python.org/3.6/library/fnmatch.html#fnmatch.fnmatch), or regular expressions.
This also applies to "sources", and "exclude" then.

It should also be clarified how "sources", "include", and "exclude" interact.
Currently "include"/"exclude" is ignored when "sources" is specified for example (which might be good to keep).
But it might make sense to have use both "include" and "exclude" together.

**Comment by RPGillespie6** [comment]
I don't think we want to use absolute paths with include/exclude pattern matching because it could lead to side effects. Consider a Linux user with username `pi_test`. If they are using fastcov `--exclude test/` they would expect it to exclude source files in the `test/` directory of their current project. However, if we compare against absolute paths, it could actually filter _all_ source files since it would match the `test/` part of `/home/pi_test/...`

I agree though that the there needs to be better documentation on how all of the different filters interact. I chose the current implementation (substring matching) over regex for simplicity and speed, but if people are wanting regex filter support I don't have anything against it. 

I'll think about how to best clarify using filtering (and or making tweaks to make it more intuitive).

**Comment by blueyed** [comment]
> I don't think we want to use absolute paths with include/exclude pattern matching

It would match against the whole, or relative path only.
E.g. `--excude test/` would be handled as `test/*` against the relative path then, or `*/test/*` against the absolute one.
For claritiy it might be good to require matching against the absolute path always.

Regular expressions would be more flexible in general (`.*/(test|src)/.*`).

**Comment by RPGillespie6** [comment]
Agree, regex would be useful to have.

**Comment by RPGillespie6** [comment]
I changed my mind on this; I think filters should compare against absolute path, so I went ahead and made the change.
