### ISSUE TITLE
Exclude lines from coverage

### ISSUE THREAD

**Issue by nlohmann** [RPGillespie6/fastcov#3]
#### My issue

It seems that code exclusions with `LCOV_EXCL_LINE` or `LCOV_EXCL_START`/`LCOV_EXCL_STOP` are ignored.

#### What I tried

Calling fastcov as described on code with exclusions like

```cpp
// LCOV_EXCL_START
if (x == nullptr) {
    assert(false);
}
// LCOV_EXCL_STOP
```

but the lines are in the report and marked as not covered.

**Comment by RPGillespie6** [comment]
I _think_ for this I may need to open every source file and scan for those markers because the JSON gcov emits has all the line syntax stripped away. The options here are to provide something like `--scan-lcov-excl` which would tell fastcov to capture marker information OR to write a drop-in replacement for `genhtml` (which might result in another speedup). I'll play around and see which one makes more sense.

Do you have an opinion?

**Comment by nlohmann** [comment]
Either way would be helpful. For my current project (see commit https://github.com/nlohmann/json/commit/b12287b36292f1895f0ded7477b397552f155776), the workflow contains several steps, and anything outside lcov would make things faster.

**Comment by RPGillespie6** [comment]
For now I'll just couple this to the `--lcov` flag because writing a static site generator to replace genhtml will take a lot longer. As long as the `--lcov` option is present, it will scan the source files for those markers and correct the coverage counts.

I should be able to fix all 3 of these issues by the end of the week.

**Comment by RPGillespie6** [comment]
Ok, I have finished implementing this feature on a branch. It _looks_ like it's working correctly, but I touched a lot of lines on this branch so I'm going to spend a bit regression testing it since I don't have an automated testing suite (yet).

**Comment by nlohmann** [comment]
I tried the branch and it works!
