### ISSUE TITLE
Support for --summary option or some other way to fail if total coverage is less than X %

### ISSUE THREAD

**Issue by f18m** [RPGillespie6/fastcov#61]
Hi,
I've been looking at the fastcov JSON output format to understand if it's possible to get a simple mesaure of "function coverage percentage" or "line coverage percentage" but apparently that's not the case.
From cobertura XML files I think we can extract easily line coverage information (from root XML node) but not the function coverage percentage.

I think it would be nice to have a way to retrieve directly from fastcov JSON these 2 numbers so that you can build a pipeline that flags the build as failed if the absolute coverage decreases under a certain threshold...

**Comment by RPGillespie6** [comment]
I think that's a good idea. Some other people are asking for niche features like this as well to accommodate their particular setup (for example, #60 requests a way to get Sonarqube specific coverage output). 

Rather than have fastcov.py be a monolithic utility that covers every possible niche use case, I think I want to try making optional "utility" scripts you can use on top of fastcov to accommodate your particular setup. This would help me from a maintenance standpoint since a separate utility script would save me from testing all the different possible permutations of fastcov CLI flags.

I created a summary utility here: https://github.com/RPGillespie6/fastcov/blob/fastcov_utils/utils/fastcov_summary.py

Please try it out and let me know if it is what you are looking for. 

Usage:
```
$ ./fastcov_summary.py coverage.json --function-coverage-threshold 80
```

(for example)

**Comment by RPGillespie6** [comment]
Alternatively, you could use fastcov's `--lcov` output flag and feed the resulting report into `genhtml` to get a function, line, and branch coverage summary. You could then use command line tools like `grep`, `cut`, and `awk` to slice up that output and fail if numbers don't meet certain threshold.

**Comment by f18m** [comment]
Hi @RPGillespie6 ,
thanks a  lot for the summary script. 
I tried it and it works just fine! 
I just stumbled over a new issue related to the combine option apparently... I will open a separate ticket for that

**Comment by f18m** [comment]
sorry I found out that there is no problem with the fastcov combine mode: I was using a wrong syntax (coming from a straight conversion of lcov original command) issuing multiple -C options (1 for each file to merge) instead of a single -C option with all .json files.
I fixed it and it works fine!

Just a suggestion: in case the fastcov_summary script finds a coverage level under threshold it prints something. However if  the coverage check is passed, it doesn't print anything... it may be useful to have instead a "function coverage threshold successful" message at the end, just to confirm that the script has understood that a check was requested..

thanks!

**Comment by f18m** [comment]
Hi @RPGillespie6 ,
do you plan to integrate this new script and make a new fastcov release soon? That would be great! Thanks!

**Comment by RPGillespie6** [comment]
Yes sorry, planning on it, but it'll need to be this weekend. I'm not quite sure how to bundle multiple scripts into a single pip module since I've never done it before, and I believe Travis CI may have disabled my CI integration due to recent terms and conditions changes, so I may also need to migrate to GitHub actions.

**Comment by f18m** [comment]
> Yes sorry, planning on it, but it'll need to be this weekend. I'm not quite sure how to bundle multiple scripts/entrypoints into a single pip module since I've never done it before, and I believe Travis CI may have disabled my CI integration due to recent terms and conditions changes, so I may also need to migrate to GitHub actions.

Great thanks - don't know if that helps but I think I did package multiple CLI scripts into the same Pypi package in the past, simply by listing the multiple scripts into the "console_scripts" entrypoint section of setup.py / .cfg

**Comment by RPGillespie6** [comment]
> it may be useful to have instead a "function coverage threshold successful" message at the end, just to confirm that the script has understood that a check was requested..

I updated script to do this before merging to master. I will also open make another PR today that updates fastcov version in PyPI

**Comment by RPGillespie6** [comment]
@f18m fastcov v1.10 is live on PyPI. You should be able to run `fastcov_summary` and `fastcov_to_sonarqube` from the CLI after installation.
