### ISSUE TITLE
Get .gcov Files

### ISSUE THREAD

**Issue by NashTools** [RPGillespie6/fastcov#62]
Thank you for the program. I was able to succesfuly generate the .html file but it seems that for SonarCloud  I need the .gcov files. Fastcov is saying, that it has processed a large number of .gcov files, but it seems they aren't being exported. Is there a way to get those .gcov files?

**Comment by RPGillespie6** [comment]
Fastcov does not process native .gcov files - it passes flags to gcov so that gcov outputs coverage information to stdout in JSON format.

That said, there is a fastcov utility that can convert fastcov JSON to Sonarqube generic coverage format, which may help here: https://github.com/RPGillespie6/fastcov/blob/master/utils/fastcov_to_sonarqube.py

I plan on adding this utility to the next PyPI release.

**Comment by RPGillespie6** [comment]
Ok, I pushed latest release to PyPI. Please try either installing latest release using pip or copying `fastcov_to_sonarqube.py` directly from this repo and see if that is an acceptable solution to your issue.

**Comment by NashTools** [comment]
Thank you, it seems to work

**Comment by RPGillespie6** [comment]
Currently the only supported output formats are fastcov json and lcov info. No plans to support raw gcov output. It's a cumbersome json format to work with.

Fastcov json schema is guaranteed to be stable for the current major version of fastcov, so I recommend using that instead. You can write your own fastcov json --> sonarqube converter if you wish.

If you really want the raw gcov output, this is the line that contains it: https://github.com/RPGillespie6/fastcov/blob/master/fastcov.py#L321
You can add a line there to dump to file, though you'll have to do a bunch of processing yourself to make it useful.
