### ISSUE TITLE
Publish this package to pypi?

### ISSUE THREAD

**Issue by noahp** [RPGillespie6/fastcov#7]
Love this tool! our coverage generation went from ~80 seconds -> ~8 seconds using it.

Would you be interested in deploying this to pypi? I've got an example patch that packages this up here: https://github.com/noahp/fastcov/commit/5ffab119ca8f369d067205f8528ea39a12f7bd9e
I can clean it up and submit a PR if you like, or feel free to take whichever changes you want.

**Comment by RPGillespie6** [comment]
Glad to hear it! 8 seconds still seems kind of high, though I guess it depends on how many cores your machine has. I have a few ideas that might be able to shave off a few more seconds (like using `ujson` if available instead of `json`).

Yes, I think it would be a good idea to publish to pypi. I guess that would finally force me to start versioning releases ;). Feel free to submit a PR if you want it expedited, otherwise I'll try to do it this weekend.

**Comment by RPGillespie6** [comment]
I believe this should be working now - let me know if I missed anything!

Check [here](https://github.com/RPGillespie6/fastcov#installation) for installation instructions.

**Comment by noahp** [comment]
Awesome, thank you!
