### ISSUE TITLE
Is there a way to use present fastcov with gcov 7?

### ISSUE THREAD

**Issue by ananthprasads** [RPGillespie6/fastcov#70]
Hi,

Is there a way to use present fastcov with gcov 7, As our project files have been compiled with gcc7, I would like to use present fastcov with gcc7. Please help me with this regard.

**Comment by latk** [comment]
No, this is not possible. Fastcov relies on gcov's JSON format, and therefore requires at least GCC 9. This is central to fastcov's design, and is the reason for it's attractive performance. Your alternatives are:

* use fastcov as of the initial commit (2d6ece2b08b6b4d0b8b463037e37727ccfd2bfec) which still supports gcov 7, but of course lacks bugfixes/features
* use a different coverage tool such as lcov or gcovr

**Comment by ananthprasads** [comment]
@latk 
Thanks for quick reply(that was pretty fast compared to any github community).  I had explored with initial commit * (HEAD detached at 2d6ece2). Is there any way to recursively run this fastcov with all files present in my project directory(similar to gcovr -r . )

Regarding usage of lcov & gcovr, I have tried them, but I am quite impressed with fastcov performance, so thought of using fastcov for our project.

**Comment by RPGillespie6** [comment]
It's not just that GCC 7 doesn't support the json intermediate format - that can be worked around by just parsing the textual gcov format. 

The main problem with GCC 7 is that it doesn't have the option of streaming the `.gcov` reports to stdout (`--stdout` in GCC 9+). Without this option, there is no easy way to run multiple instances of gcov in parallel without loss of correctness, because one instance of gcov could potentially overwrite a `.gcov` in the filesystem that another instance created before you've had a chance to parse it. The only way I can think of doing it is making N copies of the source tree (where N is the number of cores) so that each parallel gcov instance has its own private source tree, and then fastcov would then traverse each of the n source trees and parse the resulting .gcov files. I'm not even sure how that would work. I'm open to other ideas if you have any - the main reason I discontinued GCC 7.1+ support after the initial commit was because I couldn't figure out a way to guarantee correctness like I could with GCC 9+.

**Comment by RPGillespie6** [comment]
I'm going to close this issue - no plans to support GCC 7 for fastcov since it wouldn't be able to guarantee correctness.
